# Generated by Django 2.2.11 on 2020-05-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='avatare',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar.png', upload_to='images/User'),
        ),
    ]
