# Generated by Django 2.2.11 on 2020-05-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200503_0452'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('configuration', '0004_auto_20200503_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='images/avatar.png', upload_to='images/User')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.AlterModelOptions(
            name='otherinfo',
            options={'verbose_name': 'Autre', 'verbose_name_plural': 'Autres'},
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
