# Generated by Django 2.2.11 on 2020-05-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20200503_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'UserAccount', 'verbose_name_plural': 'UserAccounts'},
        ),
    ]
